version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: task_tracker_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Backend Server
  backend:
    build: ./server
    container_name: task_tracker_backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://taskapp:taskapp123@mongo:27017/task_incident_tracker?authSource=task_incident_tracker
      - JWT_SECRET=your_jwt_secret_change_in_production
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  # Frontend
  frontend:
    build: ./client
    container_name: task_tracker_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
